changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - help wanted
      - invalid
      - good first issue
      - question
      - release
      - wontfix
      - parent

  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - PBI
        - SBI

    - title: "🐛 Bug Fixes"
      labels:
        - bug

    - title: "🔨 Database Migrations"
      labels:
        - preview-migrate

    - title: "🐳 Docker Updates"
      labels:
        - docker

    - title: "⚙️ GitHub Actions"
      labels:
        - github_actions

    - title: "🧹 Maintenance"
      labels:
        - maintenance
        - refactor
        - dependencies
        - javascript

    - title: "📚 Documentation"
      labels:
        - documentation

    - title: "🔒 Security"
      labels:
        - security

    - title: "📐 Specifications"
      labels:
        - specifications

    - title: "🔧 Other"
      labels:
        - "*"
