changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: '🚀 Features'
      labels:
        - enhancement
        - PBI
        - SBI

    - title: '🐛 Bug Fixes'
      labels:
        - bug

    - title: '🔨 Database Migrations'
      labels:
        - preview-migrate

    - title: '🐳 Docker Updates'
      labels:
        - docker

    - title: '⚙️ GitHub Actions'
      labels:
        - github_actions

    - title: '🧹 Maintenance'
      labels:
        - dependencies
        - javascript
        - auto-update

    - title: '📚 Documentation'
      labels:
        - documentation

    - title: '🔒 Security'
      labels:
        - security

    - title: '📐 Specifications'
      labels:
        - specifications

    - title: '🔧 Other'
      labels:
        - '*'
