name: Slack Incoming Webhooks

on:
  release:
    types: [published]

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Prepare release notes
      id: prepare_release_notes
      run: |
        RELEASE_BODY="${{ github.event.release.body }}"
        RESULT=$(echo "$RELEASE_BODY" | grep -oP 'DEV-\d{4,5}:.*' | sed ':a;N;$!ba;s/\n/ \\n /g')
        RESULT=$(jq -Rs --arg result "$RESULT" '{"text": "A new release has been published: \($result)"}')
        echo "RESULT=$RESULT" >> $GITHUB_ENV

    - name: Send notification to Slack
      run: |
        curl -X POST -H 'Content-type: application/json' --data "$RESULT" ${{ secrets.SLACK_WEBHOOK_URL }}
