name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v4

      - name: Save release body to file
        run: echo "${{ github.event.release.body }}" > input.txt

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Prepare release notes
        id: prepare_release_notes
        run: |
          awk '/\* DEV/{print substr($0, 3)}' input.txt | awk '{printf "%s\\n ", $0}' > release_body.txt

      - name: Read Processed Release Body
        run: echo "RELEASE_BODY=$(cat release_body.txt) | sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_ENV

      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: \n ${{ env.RELEASE_BODY }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
