name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple # hoặc node/go nếu bạn dùng project đặc thù
          token: ${{ secrets.TOKEN }}
