name: Public to GitHub Gist
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v4      
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 37cfb6eb9e471dc361b385f309c5a022
          file_path: openapi/test.yaml
          file_type: yaml