name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out this repo
      - uses: actions/checkout@v4

      # Save release body to a file
      - name: Save release body to file
        run: echo "${{ github.event.release.body }}" > release_body.txt

      # Process release body to display on one line
      - name: Process release body
        run: |
          sed -i ':a;N;$!ba;s/\n/\\n /g' release_body.txt
          sed -i 's/ $//' release_body.txt

      # Read processed release body from file
      - name: Read processed release body
        id: read_release_body
        run: echo "::set-output name=RELEASE_BODY::$(cat release_body.txt)"

      # Send custom JSON data to Slack
      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published: ${{ steps.read_release_body.outputs.RELEASE_BODY }}",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: ${{ steps.read_release_body.outputs.RELEASE_BODY }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
