name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v4

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Prepare release notes
        id: prepare_release_notes
        run: |
          # Remove "## What's Changed" from the release body
          cleaned_body=$(echo "${{ github.event.release.body }}" | sed 's/## What'"'"'s Changed//g')
          echo "CLEANED_BODY=$(echo "$cleaned_body" | jq -sRr @json)" >> $GITHUB_ENV

      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published: \n ${{ env.CLEANED_BODY }}",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: \n ${{ env.CLEANED_BODY }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
