name: Slack Incoming Webhooks
on:
  # release:
  #   types: [published]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v4

      - name: list files
        run: echo ${{ github.event.release }}

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Prepare release notes
        id: prepare_release_notes
        run: |
          RELEASE_BODY="${{ github.event.release.body }}"
          RESULT=$(echo "$RELEASE_BODY" | sed 's/## What'"'"'s Changed//g' | grep -o -P 'DEV-\d{4,5}:.*' | sed 's/^/* /' | tr -d '\n' | sed 's/.$//')
          echo "RESULT=$RESULT" >> $GITHUB_ENV
      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: \n ${{ env.RESULT }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
