name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v4

      - name: Save release body to file
        run: echo "${{ github.event.release.body }}" > input.txt

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Prepare release notes
        id: prepare_release_notes
        run: |
          grep -o -P '\* DEV-\d{4,5}:.*' input.txt > release_body.txt

      - name: Read Processed Release Body
        run: |
          RELEASE_BODY=$(cat release_body.txt | jq -Rs . | tr -d '"' | tr -d '\n')
          transformed_notes=$(echo "$RELEASE_BODY" | sed -E 's|(\w+-\d+): (.+?) by @(.+?) in (https://github.com/.+?/pull/\d+)|\1<\4> : \2 by @\3|g')
          echo "transformed_notes=$transformed_notes" >> $GITHUB_ENV

      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: \n ${{ env.transformed_notes }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
