name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release notes
        id: prepare_release_notes
        run: |
          RELEASE_BODY=$(echo "${{ github.event.release.body }}" | sed 's/"/\\"/g')
          echo "::set-output name=release_body::${RELEASE_BODY}"
        shell: bash

      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "A new release has been published",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new release has been published:\n${{ steps.prepare_release_notes.outputs.release_body }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
