name: Slack Incoming Webhooks
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out this repo
      - uses: actions/checkout@v4

      - name: Save release body to file
        run: echo "${{ github.event.release.body }}"

      # Save release body to a file
      - name: Save release body to file
        run: echo "${{ github.event.release.body }}" > release_body.txt

      - name: Process Release Body
        run: |
          grep -o -P '\* DEV-\d{4,5}:.*' release_body.txt > processed_release_body.txt
          sed -i ':a;N;$!ba;s/\n/\\n/g' processed_release_body.txt  # Escaping newlines for JSON
          tr '\n' ' ' < processed_release_body.txt > single_line_release_body.txt

      # Read processed release body from file
      - name: Read Processed Release Body
        run: echo "RELEASE_BODY=$(cat single_line_release_body.txt)" >> $GITHUB_ENV

      # Send custom JSON data to Slack
      - name: Send custom JSON data to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: >
            {
                "text": "A new release has been published: \n ${{ env.RELEASE_BODY }}",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "A new release has been published: \n ${{ env.RELEASE_BODY }}"
                        }
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
